FROM python:3.10.12

WORKDIR /code


COPY  ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade pip -r /code/requirements.txt


COPY ./app/ . 


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]