FROM python:3.10.12

WORKDIR /code


RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*


COPY  /requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade pip -r /code/requirements.txt


COPY ./app/ . 


CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]